# Generated by Django 3.2.7 on 2021-09-24 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nat_ID', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=50)),
                ('dob', models.DateTimeField()),
                ('phone', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=50)),
                ('photo', models.ImageField(upload_to='couple_images/')),
                ('address', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('judge', models.CharField(help_text='Full-name of the judge who who pronounce the sentence', max_length=200)),
                ('place', models.CharField(help_text='Country/State/Disctrict or Town', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wed',
            fields=[
                ('wed_matricule', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('place', models.CharField(help_text='DRC/KINSHASA/GOMBE', max_length=200)),
                ('officer', models.CharField(help_text='Officer full-name', max_length=200)),
                ('is_divorsed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brides', to='certification.couple')),
                ('groom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grooms', to='certification.couple')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification.term')),
            ],
        ),
        migrations.CreateModel(
            name='Divorse',
            fields=[
                ('divorse_matricule', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification.sentence')),
                ('wed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification.wed')),
            ],
        ),
    ]
