# Generated by Django 3.2.7 on 2021-10-19 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_Nat_ID', models.CharField(max_length=20)),
                ('groom_full_name', models.CharField(max_length=50)),
                ('groom_dob', models.DateTimeField(blank=True, null=True)),
                ('groom_phone', models.CharField(max_length=50, unique=True)),
                ('groom_mail', models.EmailField(max_length=50, unique=True)),
                ('groom_photo', models.ImageField(upload_to='couple_images/')),
                ('groom_address', models.CharField(max_length=200)),
                ('groom_status', models.BooleanField(default=False)),
                ('bride_Nat_ID', models.CharField(max_length=20)),
                ('bride_full_name', models.CharField(max_length=50)),
                ('bride_dob', models.DateTimeField(blank=True, null=True)),
                ('bride_phone', models.CharField(max_length=50, unique=True)),
                ('bride_mail', models.EmailField(max_length=50, unique=True)),
                ('bride_photo', models.ImageField(upload_to='couple_images/')),
                ('bride_address', models.CharField(max_length=200)),
                ('bride_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Divorse',
            fields=[
                ('divorse_matricule', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sentence', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wed',
            fields=[
                ('wed_matricule', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=200)),
                ('place', models.CharField(help_text='DRC/KINSHASA/GOMBE', max_length=200)),
                ('officer', models.CharField(help_text='Officer full-name', max_length=200)),
                ('is_divorsed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification.couple')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(choices=[('Divorse', 'Divorse'), ('Marriage', 'Marriage')], help_text='Marriage costs 10$ & Divorse costs 5$', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('transaction_number', models.CharField(max_length=50)),
                ('transaction_name', models.CharField(max_length=50)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('is_done', models.BooleanField(default=False)),
                ('Divorse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certification.divorse')),
                ('mariage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certification.wed')),
            ],
        ),
        migrations.AddField(
            model_name='divorse',
            name='wed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='certification.wed'),
        ),
    ]
