# Generated by Django 3.2.7 on 2021-10-11 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_Nat_ID', models.CharField(max_length=20)),
                ('groom_full_name', models.CharField(max_length=50)),
                ('groom_dob', models.DateTimeField(blank=True, null=True)),
                ('groom_phone', models.CharField(max_length=50, unique=True)),
                ('groom_mail', models.EmailField(max_length=50, unique=True)),
                ('groom_photo', models.ImageField(upload_to='couple_images/')),
                ('groom_address', models.CharField(max_length=200)),
                ('groom_status', models.CharField(choices=[('Pending', 'Pending'), ('Married', 'Married'), ('Divorse', 'Divorse')], default='Pending', max_length=50)),
                ('bride_Nat_ID', models.CharField(max_length=20)),
                ('bride_full_name', models.CharField(max_length=50)),
                ('bride_dob', models.DateTimeField(blank=True, null=True)),
                ('bride_phone', models.CharField(max_length=50, unique=True)),
                ('bride_mail', models.EmailField(max_length=50, unique=True)),
                ('bride_photo', models.ImageField(upload_to='couple_images/')),
                ('bride_address', models.CharField(max_length=200)),
                ('bride_status', models.CharField(choices=[('Pending', 'Pending'), ('Married', 'Married'), ('Divorse', 'Divorse')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wed',
            fields=[
                ('wed_matricule', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=200)),
                ('place', models.CharField(help_text='DRC/KINSHASA/GOMBE', max_length=200)),
                ('officer', models.CharField(help_text='Officer full-name', max_length=200)),
                ('is_divorsed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification.couple')),
            ],
        ),
        migrations.CreateModel(
            name='Divorse',
            fields=[
                ('divorse_matricule', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sentence', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='certification.wed')),
            ],
        ),
    ]
