# Generated by Django 3.2.7 on 2021-09-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divorse',
            name='sentence',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wed',
            name='term',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wed',
            name='wed_matricule',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
