# Generated by Django 3.2.7 on 2021-09-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_auto_20210928_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Married', 'Married'), ('Divorse', 'Divorse')], default='Pending', max_length=50),
        ),
    ]
