# Generated by Django 3.2.7 on 2021-09-29 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0003_couple_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='Nat_ID',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='couple',
            name='dob',
            field=models.DateTimeField(default=True),
        ),
        migrations.AlterField(
            model_name='couple',
            name='mail',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='couple',
            name='phone',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='divorse',
            name='wed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='certification.wed'),
        ),
    ]
