# Generated by Django 3.2.7 on 2021-10-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0003_alter_couple_groom_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='divorse',
            name='magistrate',
            field=models.CharField(default='John Kayumbi', max_length=50),
        ),
        migrations.AddField(
            model_name='divorse',
            name='signature',
            field=models.ImageField(default='static/images/signature.jpeg', upload_to='signature/'),
        ),
    ]
