# Generated by Django 3.2.7 on 2021-11-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0004_auto_20211021_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Find',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_ID', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('requests', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
