# Generated by Django 3.2.7 on 2021-09-29 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0004_auto_20210929_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wed',
            name='bride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brides', to='certification.couple'),
        ),
        migrations.AlterField(
            model_name='wed',
            name='groom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grooms', to='certification.couple'),
        ),
    ]
