# Generated by Django 3.2.7 on 2021-11-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0006_alter_find_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_number',
        ),
    ]
