# Generated by Django 3.2.7 on 2021-11-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0007_auto_20211108_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='divorse',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wed',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
