# Generated by Django 3.2.7 on 2021-11-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0008_auto_20211108_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divorse',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='Is-Paid'),
        ),
        migrations.AlterField(
            model_name='wed',
            name='officer',
            field=models.CharField(max_length=200, verbose_name='Officer full-name'),
        ),
        migrations.AlterField(
            model_name='wed',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='Is-Paid'),
        ),
        migrations.AlterField(
            model_name='wed',
            name='place',
            field=models.CharField(max_length=200),
        ),
    ]
