# Generated by Django 3.2.7 on 2021-11-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0009_auto_20211110_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divorse',
            name='divorse_matricule',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
